// ==========================================
// 1. AUTHENTICATION ACTION TYPES
// ==========================================
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGOUT = "LOGOUT";

// ==========================================
// 2. PROJECT ACTION TYPES
// ==========================================
export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const FETCH_PROJECT_BY_ID_REQUEST = "FETCH_PROJECT_BY_ID_REQUEST";
export const FETCH_PROJECT_BY_ID_SUCCESS = "FETCH_PROJECT_BY_ID_SUCCESS";
export const FETCH_PROJECT_BY_ID_FAILURE = "FETCH_PROJECT_BY_ID_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAILURE = "SEARCH_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESS = "INVITE_TO_PROJECT_SUCCESS";
export const INVITE_TO_PROJECT_FAILURE = "INVITE_TO_PROJECT_FAILURE";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILURE = "ACCEPT_INVITATION_FAILURE";

// ==========================================
// 3. ISSUE ACTION TYPES
// ==========================================
export const FETCH_ISSUES_REQUEST = "FETCH_ISSUES_REQUEST";
export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_FAILURE = "FETCH_ISSUES_FAILURE";

export const FETCH_ISSUE_BY_ID_REQUEST = "FETCH_ISSUE_BY_ID_REQUEST";
export const FETCH_ISSUE_BY_ID_SUCCESS = "FETCH_ISSUE_BY_ID_SUCCESS";
export const FETCH_ISSUE_BY_ID_FAILURE = "FETCH_ISSUE_BY_ID_FAILURE";

export const CREATE_ISSUE_REQUEST = "CREATE_ISSUE_REQUEST";
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";
export const CREATE_ISSUE_FAILURE = "CREATE_ISSUE_FAILURE";

export const UPDATE_ISSUE_STATUS_REQUEST = "UPDATE_ISSUE_STATUS_REQUEST";
export const UPDATE_ISSUE_STATUS_SUCCESS = "UPDATE_ISSUE_STATUS_SUCCESS";
export const UPDATE_ISSUE_STATUS_FAILURE = "UPDATE_ISSUE_STATUS_FAILURE";

export const DELETE_ISSUE_REQUEST = "DELETE_ISSUE_REQUEST";
export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";
export const DELETE_ISSUE_FAILURE = "DELETE_ISSUE_FAILURE";

export const ASSIGNED_ISSUE_TO_USER_REQUEST = "ASSIGNED_ISSUE_TO_USER_REQUEST";
export const ASSIGNED_ISSUE_TO_USER_SUCCESS = "ASSIGNED_ISSUE_TO_USER_SUCCESS";
export const ASSIGNED_ISSUE_TO_USER_FAILURE = "ASSIGNED_ISSUE_TO_USER_FAILURE";

// ==========================================
// 4. COMMENT ACTION TYPES
// ==========================================
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";

// ==========================================
// 5. CHAT ACTION TYPES
// ==========================================
export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const FETCH_CHAT_BY_PROJECT_REQUEST = "FETCH_CHAT_BY_PROJECT_REQUEST";
export const FETCH_CHAT_BY_PROJECT_SUCCESS = "FETCH_CHAT_BY_PROJECT_SUCCESS";
export const FETCH_CHAT_BY_PROJECT_FAILURE = "FETCH_CHAT_BY_PROJECT_FAILURE";

export const FETCH_CHAT_MESSAGES_REQUEST = "FETCH_CHAT_MESSAGES_REQUEST";
export const FETCH_CHAT_MESSAGES_SUCCESS = "FETCH_CHAT_MESSAGES_SUCCESS";
export const FETCH_CHAT_MESSAGES_FAILURE = "FETCH_CHAT_MESSAGES_FAILURE";

// ==========================================
// 6. SUBSCRIPTION ACTION TYPES
// ==========================================
export const GET_USER_SUBSCRIPTION_REQUEST = "GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS = "GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE = "GET_USER_SUBSCRIPTION_FAILURE";

export const UPGRADE_SUBSCRIPTION_REQUEST = "UPGRADE_SUBSCRIPTION_REQUEST";
export const UPGRADE_SUBSCRIPTION_SUCCESS = "UPGRADE_SUBSCRIPTION_SUCCESS";
export const UPGRADE_SUBSCRIPTION_FAILURE = "UPGRADE_SUBSCRIPTION_FAILURE";
